name: EBS Deployment
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/Checkout@v4

      - name: Run unit test
        run: |
          docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
          docker image build . -t kodega2016/react-app:dev -f Dockerfile.dev
          docker container run -e CI=true kodega2016/react-app:dev npm run test
